//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL.Repos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SY_KEY_VALUES
    {
        public string key_id { get; set; }
        public string key_type { get; set; }
        public string key_name { get; set; }
        public string key_value { get; set; }
        public string key_active { get; set; }
        public string Parent_KyeID { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> FileSize { get; set; }
        public string IsYesNoReq { get; set; }
        public string MasterTableName { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> PortalID { get; set; }
    }
}
