//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL.Repos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_USERMASTER
    {
        public decimal UserId { get; set; }
        public string User_Type { get; set; }
        public string User_Type_Code { get; set; }
        public string EmpCode { get; set; }
        public string EmpName { get; set; }
        public string EmailId { get; set; }
        public Nullable<decimal> DeptId { get; set; }
        public Nullable<decimal> BranchId { get; set; }
        public string Login_Password { get; set; }
        public Nullable<int> Password_Expiry_Days { get; set; }
        public Nullable<System.DateTime> Password_Expiry_Date { get; set; }
        public Nullable<int> Attempt_Count { get; set; }
        public Nullable<System.DateTime> Last_LogIn_DateTime { get; set; }
        public string IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string Login_IPAddress { get; set; }
        public Nullable<decimal> SBUID { get; set; }
        public string LevelNum { get; set; }
        public Nullable<decimal> FunctionID { get; set; }
        public string IsGetBranchMail { get; set; }
        public string JISource { get; set; }
        public string Old_EmailId { get; set; }
        public Nullable<int> CityID { get; set; }
        public string PortalID { get; set; }
        public string Mobile_No { get; set; }
        public string LandLine_No { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public Nullable<System.DateTime> Date_Of_Joining { get; set; }
        public string Plant_Id { get; set; }
        public string Entity_Id { get; set; }
        public string Level_Selection_Id { get; set; }
        public string Approver_Selection_Id { get; set; }
        public string ForgotPassword { get; set; }
        public string RoleID { get; set; }
        public string Approver_Level_Id { get; set; }
    }
}
