//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL.Repos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_VendorGSTMapping
    {
        public int ID { get; set; }
        public Nullable<int> SBUId { get; set; }
        public Nullable<int> venderId { get; set; }
        public string AccountCode { get; set; }
        public string Supplier_StateCode { get; set; }
        public string GSTTypeKey { get; set; }
        public string GST_TAXCode { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> StateCode { get; set; }
        public string Supptype { get; set; }
        public string EmailId { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> VendorCityID { get; set; }
        public string VendorPincode { get; set; }
        public string ContactNo { get; set; }
        public string CompanyBankAcc { get; set; }
        public string BankName { get; set; }
        public string IFSCCode { get; set; }
    }
}
