//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL.Repos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PincodeMaster
    {
        public int PID { get; set; }
        public Nullable<decimal> Pincode { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public string CityName { get; set; }
        public string StateName { get; set; }
    }
}
