//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL.Repos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_VendorRegist_DocDetails_Hist
    {
        public int HistID { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<int> RegID { get; set; }
        public string DocTypeKey { get; set; }
        public string DocName { get; set; }
        public string DocPath { get; set; }
        public Nullable<decimal> DocSize { get; set; }
        public string DocValue { get; set; }
        public string YesNoStatus { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> HistDate { get; set; }
        public Nullable<int> HistBy { get; set; }
        public string HistType { get; set; }
    }
}
