//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL.Repos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RejectionMatrix
    {
        public int ID { get; set; }
        public string VendorID { get; set; }
        public string PlantID { get; set; }
        public string DepartmentID { get; set; }
        public string POType { get; set; }
        public Nullable<int> RejectorUserID { get; set; }
        public string RejectionMailID { get; set; }
        public Nullable<int> LevelID { get; set; }
        public string IsNCUserType { get; set; }
    }
}
