//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL.Repos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_VENDORMASATER
    {
        public decimal VendorId { get; set; }
        public Nullable<int> RegID { get; set; }
        public string AccountCode { get; set; }
        public string VendorName { get; set; }
        public Nullable<decimal> SBUId { get; set; }
        public string VendorAdd { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string PIN { get; set; }
        public string PAN { get; set; }
        public string Telephone { get; set; }
        public Nullable<decimal> MobileNo1 { get; set; }
        public Nullable<decimal> MobileNo2 { get; set; }
        public string ContactPerson { get; set; }
        public string ContactPersonDesig { get; set; }
        public string OrgTypeKey { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
