//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL.Repos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GRNMaster_021121
    {
        public int ID { get; set; }
        public string PONo { get; set; }
        public Nullable<int> GRNSrNo { get; set; }
        public string GRNNo { get; set; }
        public string DeliveryLocation { get; set; }
        public Nullable<int> DeliveryLocationID { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<int> ReceivedBy { get; set; }
    }
}
