//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL.Repos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_VendorRequisition
    {
        public int ID { get; set; }
        public string TicketNo { get; set; }
        public Nullable<System.DateTime> Query_Date { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string Query_Type { get; set; }
        public string Query_SubType { get; set; }
        public string Ref { get; set; }
        public string Query_Desc { get; set; }
        public string Error_Severity { get; set; }
        public string Error_Type { get; set; }
        public string Error_Acceptance { get; set; }
        public string User_Comment { get; set; }
        public string CAPA_Required { get; set; }
        public string CAPA_RootCause { get; set; }
        public string Corrective_Action { get; set; }
        public string Preventive_Action { get; set; }
        public string IS_Status { get; set; }
        public string Attachment { get; set; }
        public string IS_Delete { get; set; }
        public Nullable<int> IS_UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedON { get; set; }
    }
}
