//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL.Repos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DASHBOARD_Queue
    {
        public int ID { get; set; }
        public string Queue_Name { get; set; }
        public Nullable<int> Order_ID { get; set; }
        public string IS_Active { get; set; }
    }
}
