//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL.Repos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_INVOICETYPEMASTER
    {
        public decimal InvoiceTypeID { get; set; }
        public string InvoiceType { get; set; }
        public Nullable<decimal> SBUId { get; set; }
        public string IsActive { get; set; }
        public string CategoryType { get; set; }
        public Nullable<decimal> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<decimal> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<decimal> FunctionID { get; set; }
        public string Level1 { get; set; }
    }
}
