//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL.Repos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_InvoiceApprovalMatrix_AP
    {
        public int ID { get; set; }
        public string VendorId { get; set; }
        public Nullable<int> PlantID { get; set; }
        public Nullable<int> DeptID { get; set; }
        public string POType { get; set; }
        public Nullable<decimal> MinAmnt { get; set; }
        public Nullable<decimal> MaxAmnt { get; set; }
        public Nullable<int> L1_ApprovalID { get; set; }
        public Nullable<int> L2_ApprovalID { get; set; }
        public Nullable<int> L3_ApprovalID { get; set; }
    }
}
