//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL.Repos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_BarcodeGenMaster
    {
        public int ID { get; set; }
        public Nullable<int> BarcodeGenID { get; set; }
        public string Barcode { get; set; }
        public string IS_Received { get; set; }
        public Nullable<int> Received_By { get; set; }
        public Nullable<System.DateTime> ReceivedOn { get; set; }
        public string IS_Consumed { get; set; }
        public Nullable<int> Consumed_By { get; set; }
        public Nullable<System.DateTime> ConsumedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string IS_Discard { get; set; }
        public Nullable<int> DiscardBy { get; set; }
        public Nullable<System.DateTime> DiscardOn { get; set; }
        public string Discard_Reason { get; set; }
    }
}
