//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL.Repos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Query_DesMaster
    {
        public string key_id { get; set; }
        public string key_name { get; set; }
        public string key_active { get; set; }
        public string Parent_KyeID { get; set; }
    }
}
