//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL.Repos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_LOCATIONMASTER
    {
        public decimal LocationId { get; set; }
        public string LocationName { get; set; }
        public decimal BranchId { get; set; }
        public string LocationAdd { get; set; }
        public string LocationType { get; set; }
        public string IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> Updatedy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
