//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL.Repos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GLCodeMaster_021121
    {
        public int ID { get; set; }
        public string HSNSACCode { get; set; }
        public string GLCode { get; set; }
        public string Description { get; set; }
        public string IsActive { get; set; }
    }
}
