//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL.Repos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_INVOICESTAGINGDATA
    {
        public decimal StagingID { get; set; }
        public string Layout_Identifier { get; set; }
        public string InvoiceCode { get; set; }
        public string IsTDS { get; set; }
        public string IsService { get; set; }
        public string IsRCM { get; set; }
        public string IsNoTax { get; set; }
        public Nullable<System.DateTime> InvoiceRecDateTime { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string InvoiceNum { get; set; }
        public string VendorCode { get; set; }
        public string VendorPAN { get; set; }
        public string SBUID { get; set; }
        public string Ledger { get; set; }
        public string ExpenseType { get; set; }
        public string Period { get; set; }
        public string ExpenseCode { get; set; }
        public Nullable<decimal> TransactionAmount { get; set; }
        public string Debit_Credit { get; set; }
        public string CurrencyType { get; set; }
        public string Narration { get; set; }
        public Nullable<System.DateTime> InvoiceFromDate { get; set; }
        public Nullable<System.DateTime> InvoiceToDate { get; set; }
        public string ApplicationFinYear { get; set; }
        public string CountOfQty { get; set; }
        public string UOM { get; set; }
        public string DataEntryLocation { get; set; }
        public string SBU_BL_PRD { get; set; }
        public string JobNumberCode { get; set; }
        public string EmpCode { get; set; }
        public string TaxCode { get; set; }
        public string AdditionalMiscCode { get; set; }
        public string FOLL_BR { get; set; }
        public string COACode { get; set; }
        public string LocationCode { get; set; }
        public string TypeOfServices { get; set; }
        public string FollowUpDetails { get; set; }
        public string FCL_LCL { get; set; }
        public string FillingNum { get; set; }
        public string UserID { get; set; }
        public string FileVoucherNum { get; set; }
        public string JISources { get; set; }
        public string CONVERSIONRATE { get; set; }
        public Nullable<decimal> BASEAMTINR { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string TaxCodeData { get; set; }
        public string RowType { get; set; }
    }
}
