//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL.Repos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PO_DETAILS
    {
        public int DETAIL_ID { get; set; }
        public Nullable<int> PO_ID { get; set; }
        public Nullable<int> ITEM_ID { get; set; }
        public Nullable<int> LineSeqNo { get; set; }
        public string ItemCode { get; set; }
        public string ITEM_DESC { get; set; }
        public Nullable<int> ITEM_PARENT_ID { get; set; }
        public string ITEM_PARENT_DESC { get; set; }
        public string UOM { get; set; }
        public Nullable<decimal> GSTPercentage { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
        public Nullable<decimal> RATE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string LINE_DESC { get; set; }
        public string ITEM_COMMENTS { get; set; }
        public Nullable<int> ENTRY_ID { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
        public Nullable<int> MODIFY_ID { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public Nullable<int> REQ_ID { get; set; }
        public Nullable<int> REQ_DETAIL_ID { get; set; }
        public Nullable<int> CONTRACT_ID { get; set; }
        public Nullable<int> CONTRACT_DETAIL_ID { get; set; }
        public Nullable<int> RFQ_ID { get; set; }
        public Nullable<int> RFQ_DETAIL_ID { get; set; }
        public Nullable<int> QUOTATION_ID { get; set; }
        public Nullable<int> QUOTATION_DETAIL_ID { get; set; }
        public Nullable<int> CUR_ID { get; set; }
        public string CUR_DESC { get; set; }
        public Nullable<bool> CUR_OVERRIDE { get; set; }
        public Nullable<decimal> CUR_RATE { get; set; }
        public Nullable<decimal> BASE_AMOUNT { get; set; }
        public Nullable<decimal> TOTALTAX { get; set; }
        public Nullable<int> TAXID1 { get; set; }
        public string TAXNAME1 { get; set; }
        public Nullable<decimal> TAXPER1 { get; set; }
        public Nullable<bool> TAXCOMP1 { get; set; }
        public Nullable<decimal> TAXAMT1 { get; set; }
        public Nullable<int> TAXID2 { get; set; }
        public string TAXNAME2 { get; set; }
        public Nullable<decimal> TAXPER2 { get; set; }
        public Nullable<bool> TAXCOMP2 { get; set; }
        public Nullable<decimal> TAXAMT2 { get; set; }
        public Nullable<int> TAXID3 { get; set; }
        public string TAXNAME3 { get; set; }
        public Nullable<decimal> TAXPER3 { get; set; }
        public Nullable<bool> TAXCOMP3 { get; set; }
        public Nullable<decimal> TAXAMT3 { get; set; }
        public Nullable<int> TAXID4 { get; set; }
        public string TAXNAME4 { get; set; }
        public Nullable<decimal> TAXPER4 { get; set; }
        public Nullable<bool> TAXCOMP4 { get; set; }
        public Nullable<decimal> TAXAMT4 { get; set; }
        public Nullable<int> TAXID5 { get; set; }
        public string TAXNAME5 { get; set; }
        public Nullable<decimal> TAXPER5 { get; set; }
        public Nullable<bool> TAXCOMP5 { get; set; }
        public Nullable<decimal> TAXAMT5 { get; set; }
        public Nullable<decimal> PR_QTY { get; set; }
        public Nullable<decimal> PR_RATE { get; set; }
        public Nullable<decimal> PR_AMOUNT { get; set; }
        public Nullable<decimal> GST_Amount { get; set; }
        public string TDS_CODE { get; set; }
        public Nullable<decimal> TDS_AMOUNT { get; set; }
        public Nullable<decimal> TAX_ON { get; set; }
        public string ADD_CHARGES_1_CODE { get; set; }
        public string ADD_CHARGES_1_DESC { get; set; }
        public Nullable<decimal> ADD_CHARGES_1_AMT { get; set; }
        public string ADD_CHARGES_2_CODE { get; set; }
        public string ADD_CHARGES_2_DESC { get; set; }
        public Nullable<decimal> ADD_CHARGES_2_AMT { get; set; }
        public Nullable<decimal> ADD_CHARGES_TOTAL { get; set; }
        public Nullable<decimal> LINE_TOTAL { get; set; }
        public string SERVICE_TAX_CODE { get; set; }
        public string PO_No { get; set; }
    }
}
