//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL.Repos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_APPROVALSTATUS
    {
        public decimal ID { get; set; }
        public string InvoiceCode { get; set; }
        public Nullable<decimal> LevelID { get; set; }
        public string EmpCode { get; set; }
        public Nullable<decimal> FunctionID { get; set; }
        public string ApprovalStatus { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public Nullable<System.DateTime> ApprovalSentOn { get; set; }
        public string MailSentStatus { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> AppNextLvl { get; set; }
        public string RejMailStatus { get; set; }
        public Nullable<System.DateTime> RejMailSentOn { get; set; }
    }
}
