//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL.Repos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_INVOTAXCODEMAP
    {
        public decimal MappingId { get; set; }
        public Nullable<decimal> InvoiceTypeId { get; set; }
        public string TaxCodeChar { get; set; }
    }
}
