//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL.Repos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OCRInvoiceItemDetails
    {
        public int ID { get; set; }
        public string InwardID { get; set; }
        public string PONo { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<decimal> InvoiceNetAmt { get; set; }
        public Nullable<decimal> TaxAmt { get; set; }
        public string ItemCode { get; set; }
        public string Description { get; set; }
        public string HSNCode { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> GSTAmount { get; set; }
        public Nullable<decimal> GrossAmt { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public Nullable<decimal> GSTPercentage { get; set; }
        public Nullable<decimal> DiscountPercent { get; set; }
        public string IsOldOCRValue { get; set; }
    }
}
