//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL.Repos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RejectionDetails_MailRoom
    {
        public int RejID { get; set; }
        public string InwardID { get; set; }
        public Nullable<int> RejectID { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string IsLocked { get; set; }
        public Nullable<int> LockedBy { get; set; }
        public Nullable<System.DateTime> LockedDate { get; set; }
        public string ValidateStatus { get; set; }
        public Nullable<int> ValidateRejectID { get; set; }
        public string ValidateRemark { get; set; }
        public Nullable<System.DateTime> ValidateDate { get; set; }
        public Nullable<int> ValidateBy { get; set; }
        public string IsTrash { get; set; }
    }
}
