//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL.Repos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GRNItemDetails_230222
    {
        public int ID { get; set; }
        public Nullable<int> GRNID { get; set; }
        public string PONo { get; set; }
        public string GRNNo { get; set; }
        public Nullable<int> LineSeqNo { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> ItemQty { get; set; }
        public Nullable<decimal> ItemRate { get; set; }
        public Nullable<decimal> ItemAmount { get; set; }
        public Nullable<decimal> ItemGST { get; set; }
        public Nullable<decimal> ItemGSTRate { get; set; }
        public string ItemRemark { get; set; }
        public Nullable<System.DateTime> ItemRecDate { get; set; }
        public Nullable<int> ItemRecBy { get; set; }
        public Nullable<decimal> GSTPercentage { get; set; }
        public string GRNStatus { get; set; }
        public Nullable<System.DateTime> GRNStatusDate { get; set; }
        public Nullable<int> GRNStatusBy { get; set; }
        public string StatusRemark { get; set; }
    }
}
