//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL.Repos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RejectionMaster_MailRoom
    {
        public int RejID { get; set; }
        public string RejectCode { get; set; }
        public string RejectName { get; set; }
        public string RejectionAt { get; set; }
        public string IsActive { get; set; }
    }
}
