//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL.Repos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_apikey
    {
        public int id { get; set; }
        public string Apikey { get; set; }
        public Nullable<int> UsedCount { get; set; }
        public string Isactive { get; set; }
        public string Emailid { get; set; }
    }
}
